Repository anantjakhmola/Data_Structure_Codes, pull requests merged in 2020-10, with the labels that each got.

#4 Added queue in Javascript Language
  queue_in_js/queue.js
Labels: documentation, hacktoberfest-accepted

#5 Added Queue in java
  queue_in_java/queue.java
Labels: enhancement, hacktoberfest-accepted

#6 Added stack code in java language
  stack_in_java/stack.java
Labels: documentation, hacktoberfest-accepted

#7 Added Stack in TypeScript
  stack_in_ts/stack.ts
Labels: documentation, enhancement, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted
